# Generated by Django 6.1.1 on 2026-09-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowers_name', models.CharField(max_length=200)),
                ('destination', models.TextField()),
                ('borrow_time', models.DateTimeField()),
                ('fuel_percent', models.IntegerField()),
                ('current_mileage', models.IntegerField()),
                ('return_time', models.DateTimeField()),
                ('time_borrowed', models.DurationField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
    ]
