# Generated by Django 6.1.1 on 2026-09-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowDetails',
            new_name='BorrowDetail',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
