# Generated by Django 6.1.1 on 2026-09-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_borrowdetails_borrowdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowdetail',
            name='return_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='time_borrowed',
            field=models.DurationField(blank=True),
        ),
    ]
