# Generated by Django 6.1.1 on 2026-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_borrowdetail_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowdetail',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='time_borrowed',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
