# Generated by Django 6.1.1 on 2026-09-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_borrowdetail_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowdetail',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
