# Generated by Django 6.1.1 on 2026-09-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_borrowdetail_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowdetail',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
