# Generated by Django 6.1.1 on 2026-09-15 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_borrowdetail_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowdetail',
            name='fuel_percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
