# Generated by Django 6.1.1 on 2026-09-16 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_borrowdetail_fuel_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowdetail',
            name='time_borrowed',
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='borrow_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='fuel_percent',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
