# Generated by Django 6.1.1 on 2026-09-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_remove_borrowdetail_time_borrowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowdetail',
            old_name='return_time',
            new_name='actual_return_time',
        ),
        migrations.RenameField(
            model_name='borrowdetail',
            old_name='car_name',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available',
        ),
        migrations.AddField(
            model_name='borrowdetail',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowers_name', models.CharField(max_length=200)),
                ('destination', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
