# Generated by Django 6.1.1 on 2026-09-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_rename_return_time_borrowdetail_actual_return_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdetail',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowdetail',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='vehicles.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowdetail',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
